
import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  widgetSidebar: [
    {
      type: "autogenerated",
      dirName: "widget-config",
    },
  ],
  apisidebar: require("./developer_docs/api/sidebar.ts").default
};

export default sidebars;
