import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const generatedApiSidebar = require("./docs/api/sidebar.ts").default as any[];
const analyticsOrder = [
  "api/obtener-analitica-del-proyecto",
  "api/listar-conversaciones-del-proyecto",
  "api/obtener-detalle-de-una-conversacion",
  "api/registrar-evento-analitico",
];
const analyticsOrderIndex = new Map(
  analyticsOrder.map((id, index) => [id, index]),
);
const orderedApiSidebar = generatedApiSidebar.map((item) =>
  item.type === "category" && item.link?.id === "api/analytics"
    ? {
        ...item,
        items: [...item.items].sort((a: any, b: any) => {
          const aIndex = analyticsOrderIndex.get(a.id) ?? Number.MAX_SAFE_INTEGER;
          const bIndex = analyticsOrderIndex.get(b.id) ?? Number.MAX_SAFE_INTEGER;
          return aIndex - bIndex;
        }),
      }
    : item,
);

const sidebars: SidebarsConfig = {
  docsSidebar: [
    "intro",
    "what-is-aifindr",
    "how-it-works",
    {
      type: "category",
      label: "Cómo se integra",
      customProps: {
        icon: "Plug01Icon",
      },
      link: {
        type: "doc",
        id: "integration",
      },
      items: [
        {
          type: "category",
          label: "Widget",
          items: [
            "widget-config/intro",
            "widget-config/instalacion",
            "widget-config/personalizacion",
            "widget-config/contexto-metadatos",
            "widget-config/javascript-api",
            "widget-config/events-triggers",
            {
              type: "category",
              label: "Integraciones",
              items: [
                {
                  type: "autogenerated",
                  dirName: "widget-config/integraciones",
                },
              ],
            },
          ],
        },
        {
          type: "category",
          label: "API",
          items: orderedApiSidebar,
        },
      ],
    },
    "security",
  ],
};

export default sidebars;
