import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const generatedApiSidebar = require("./docs/api/sidebar.ts").default as any[];
const apiSidebar = generatedApiSidebar.map((item) =>
  item.type === "category" && item.link?.id === "api/analytics"
    ? {
        ...item,
        items: ["api/private-analytics-api", ...item.items],
      }
    : item,
);

const sidebars: SidebarsConfig = {
  docsSidebar: [
    "intro",
    "what-is-aifindr",
    "how-it-works",
    {
      type: "category",
      label: "Cómo se integra",
      customProps: {
        icon: "Plug01Icon",
      },
      link: {
        type: "doc",
        id: "integration",
      },
      items: [
        {
          type: "category",
          label: "Widget",
          items: [
            "widget-config/intro",
            "widget-config/instalacion",
            "widget-config/personalizacion",
            "widget-config/contexto-metadatos",
            "widget-config/javascript-api",
            "widget-config/events-triggers",
            {
              type: "category",
              label: "Integraciones",
              items: [
                {
                  type: "autogenerated",
                  dirName: "widget-config/integraciones",
                },
              ],
            },
          ],
        },
        {
          type: "category",
          label: "API",
          items: apiSidebar,
        },
      ],
    },
    "security",
  ],
};

export default sidebars;
