/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check
import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {type: "doc", id: "intro"},
    { type: "autogenerated", dirName: "tutorial-basics" },
    { type: "autogenerated", dirName: "tutorial-extras" },
  ],
  openApiSidebar: [
    {
      type: "category",
      label: "AI Findr",
      link: {
        type: "generated-index",
        title: "AI Findr API",
        description:
        "The AI Findr API provides programmatic access to our platform. Build custom integrations to deliver AI-powered conversational experiences using your own content knowledge base. Perfect for developers who need direct backend integration instead of our widget solution. Key features include conversational AI with streaming responses, content ingestion and management, conversation analytics and insights, and customizable branding and styling. Used by banks for customer support automation and retail spaces for location and service inquiries.",
        slug: "/category/aifindr-api"
      },
      items: require("./docs/aifindr/sidebar.js")
    }
  ]
};

export default sidebars;
